### ISSUE TITLE
Date type not have Type Adapter

### ISSUE THREAD

**Issue by jmsuarez2005** [chalup/microorm#11]
the solutions is create DateAdapter in **TypeAdapters file**. It is a source

 public static class DateAdapter implements TypeAdapter<Date> {
    @Override
    public Date fromCursor(Cursor c, String columnName) {
      return new Date(c.getLong(c.getColumnIndexOrThrow(columnName))*1000);
    }
    @Override
    public void toContentValues(ContentValues values, String columnName, Date object) {
      values.put(columnName, object);
    }
  }

**Comment by chalup** [comment]
Two things:

1. I recommend using JodaTime or ThreeTenBp instead of `java.util.Date` or `java.util.Calendar`.
2. Your `toContentValues` implementation doesn't compile, you probably want something like `values.put(columnName, object.getTime());`.
