### ISSUE TITLE
Type Timestamp not supported

### ISSUE THREAD

**Issue by q0re** [chalup/microorm#12]
Works very good, but type timestamp (Java.sql) is not supported. 
For example:
`@Column("created")`
`private Timestamp created;`

And it would be nice if the column name is the same as the name of the variable that it works per default.

**Comment by chalup** [comment]
The library provides `TypeAdapter`s only for bare minimum of classes. If you need anything more than this, you have to specify the appropriate type adapters yourself. Check the https://github.com/chalup/microorm/blob/master/library/src/test/java/org/chalup/microorm/tests/CustomTypeAdapterTest.java to see how to do this.

Regarding your second point: I considered this, but then you have to deal with `createdAt` fields, which is probably represented by `created_at` column in sql table and things get complicated pretty fast. For the forseeable future you'll have to explicitly specify column name.
